





<a-asset-item id="platform" response-type="arraybuffer" position="0 0 -5" src="/assets/models/2022Summits/9SidedPlatform.glb">
</a-asset-item>
<a-asset-item id="edtownhall" response-type="arraybuffer" src="/assets/models/2022Summits/EdTownHall.glb"></a-asset-item>
<a-asset-item id="emblem" response-type="arraybuffer" src="/assets/models/emblem2022.glb"></a-asset-item>
<a-asset-item id="chair" response-type="arraybuffer" src="/assets/models/chair.glb"></a-asset-item>
<!--
<a-asset-item id="22SummitsSquare" response-type="arraybuffer" src="/assets/models/2022Summits/2022WebXRSummitSeriesSquare.glb"></a-asset-item>-->
<!--LIST OF ASSETS GENERATED BY MENU-->

<?php
    $skybox_id = get_post_meta($post->ID,"skybox",true);
    //var_dump($skybox_id);
   $skybox = str_replace("-scaled","",getThumbnail($skybox_id));
   if($skybox_id != ""){

?>
   <img id="sky" src="<?=$skybox?>">
<?php
    }



   if(@$assets3D){// this var is created in panels.php
    foreach($assets3D as $key => $asset3D){
        ?>
<!-- ASSET <?=$asset3D['slug']?> -->
    <a-asset-item id="<?=$asset3D['slug']?>-logo3D" response-type="arraybuffer" src="<?=$asset3D['asset']?>"></a-asset-item>

            <?php
        }
    }

    ?>




<?php
    if(is_array(@$assets)){
        foreach($assets as $key => $asset){
         extract($asset);
            ?>
<a-asset-item id="<?=$slug?>" response-type="arraybuffer" src="<?=$path?>"></a-asset-item>
            <?php
        }
    }
?>